// <auto-generated />
using System;
using FamilyOs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyOs.Infrastructure.Persistence.Migrations;

[DbContext(typeof(FamilyOsDbContext))]
partial class FamilyOsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("app")
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.HasPostgresEnum("app", "user_role", new[] { "Admin", "Adult", "Child" });
        modelBuilder.HasPostgresEnum("app", "relation", new[] { "Self", "Spouse", "Child", "Parent", "Other" });

        modelBuilder.Entity("FamilyOs.Domain.Entities.FamilyMember", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateOnly?>("BirthDate")
                .HasColumnType("date")
                .HasColumnName("birth_date");

            b.Property<DateTime>("CreatedUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_utc");

            b.Property<DateTime?>("DeletedUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("deleted_utc");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("text")
                .HasColumnName("display_name");

            b.Property<string>("FullName")
                .HasMaxLength(200)
                .HasColumnType("text")
                .HasColumnName("full_name");

            b.Property<bool>("HasUserAccount")
                .HasColumnType("boolean")
                .HasColumnName("has_user_account");

            b.Property<string>("Notes")
                .HasColumnType("text")
                .HasColumnName("notes");

            b.Property<int>("Relation")
                .HasColumnType("integer")
                .HasColumnName("relation");

            b.Property<DateTime>("UpdatedUtc")
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_utc");

            b.Property<uint>("xmin")
                .IsConcurrencyToken()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("xid")
                .HasColumnName("xmin");

            b.HasKey("Id")
                .HasName("pk_family_member");

            b.HasIndex("HasUserAccount")
                .HasDatabaseName("ix_family_member_has_user_account")
                .HasFilter("deleted_utc IS NULL");

            b.HasIndex("Relation")
                .HasDatabaseName("ix_family_member_relation")
                .HasFilter("deleted_utc IS NULL");

            b.ToTable("family_member", "app", t =>
            {
                t.HasCheckConstraint("ck_family_member_birth_date", "birth_date IS NULL OR birth_date <= current_date");
                t.HasCheckConstraint("ck_family_member_display_name_len", "char_length(display_name) BETWEEN 1 AND 100");
                t.HasCheckConstraint("ck_family_member_full_name_len", "full_name IS NULL OR char_length(full_name) <= 200");
            });
        });

        modelBuilder.Entity("FamilyOs.Domain.Entities.PendingInvite", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_utc");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(320)
                .HasColumnType("character varying(320)")
                .HasColumnName("email");

            b.Property<Guid>("FamilyMemberId")
                .HasColumnType("uuid")
                .HasColumnName("family_member_id");

            b.Property<string>("Role")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("role");

            b.HasKey("Id")
                .HasName("pk_pending_invite");

            b.HasIndex("Email")
                .IsUnique()
                .HasDatabaseName("ux_pending_invite_email");

            b.ToTable("pending_invite", "app");
        });

        modelBuilder.Entity("FamilyOs.Domain.Entities.RevokedSession", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("RevokedUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("revoked_utc");

            b.Property<string>("SessionId")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("session_id");

            b.HasKey("Id")
                .HasName("pk_revoked_session");

            b.HasIndex("SessionId")
                .IsUnique()
                .HasDatabaseName("ix_revoked_session_session_id");

            b.ToTable("revoked_session", "app");
        });

        modelBuilder.Entity("FamilyOs.Domain.Entities.UserAccount", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_utc");

            b.Property<DateTime?>("DeletedUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("deleted_utc");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("text")
                .HasColumnName("display_name");

            b.Property<bool>("EmailEnabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true)
                .HasColumnName("email_enabled");

            b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("email");

            b.Property<Guid>("FamilyMemberId")
                .HasColumnType("uuid")
                .HasColumnName("family_member_id");

            b.Property<string>("GoogleSubject")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("google_subject");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");

            b.Property<DateTime?>("LastLoginUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_login_utc");

            b.Property<string>("QuietHoursEnd")
                .HasMaxLength(5)
                .HasColumnType("character varying(5)")
                .HasColumnName("quiet_hours_end");

            b.Property<string>("QuietHoursStart")
                .HasMaxLength(5)
                .HasColumnType("character varying(5)")
                .HasColumnName("quiet_hours_start");

            b.Property<int>("Role")
                .HasColumnType("integer")
                .HasColumnName("role");

            b.Property<DateTime>("UpdatedUtc")
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_utc");

            b.Property<uint>("xmin")
                .IsConcurrencyToken()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("xid")
                .HasColumnName("xmin");

            b.HasKey("Id")
                .HasName("pk_user_account");

            b.HasIndex("Email")
                .IsUnique()
                .HasDatabaseName("ux_user_account_email")
                .HasFilter("deleted_utc IS NULL");

            b.HasIndex("FamilyMemberId")
                .IsUnique()
                .HasDatabaseName("ix_user_account_family_member_id");

            b.HasIndex("GoogleSubject")
                .IsUnique()
                .HasDatabaseName("ux_user_account_google_subject")
                .HasFilter("deleted_utc IS NULL");

            b.HasIndex("IsActive")
                .HasDatabaseName("ix_user_account_is_active")
                .HasFilter("deleted_utc IS NULL");

            b.ToTable("user_account", "app", t =>
            {
                t.HasCheckConstraint("ck_user_account_email_lower", "email = lower(email)");
            });
        });

        modelBuilder.Entity("FamilyOs.Domain.Entities.UserAccount", b =>
        {
            b.HasOne("FamilyOs.Domain.Entities.FamilyMember", "FamilyMember")
                .WithOne("UserAccount")
                .HasForeignKey("FamilyOs.Domain.Entities.UserAccount", "FamilyMemberId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("FamilyMember");
        });

        modelBuilder.Entity("FamilyOs.Domain.Entities.FamilyMember", b =>
        {
            b.Navigation("UserAccount");
        });
#pragma warning restore 612, 618
    }
}
